# Generated by Django 6.0.1 on 2026-01-31 08:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaknessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_a', models.TextField()),
                ('response_b', models.TextField()),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('ai_logic', models.TextField(blank=True)),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rater.prompt')),
                ('weaknesses_a', models.ManyToManyField(blank=True, related_name='a_flaws', to='rater.weaknesscategory')),
                ('weaknesses_b', models.ManyToManyField(blank=True, related_name='b_flaws', to='rater.weaknesscategory')),
            ],
        ),
    ]
