# Generated by Django 6.0.1 on 2026-01-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaknesscategory',
            name='description',
            field=models.TextField(blank=True, help_text='Why is this a weakness?'),
        ),
        migrations.AddField(
            model_name='weaknesscategory',
            name='examples',
            field=models.TextField(blank=True, help_text='Plain text examples for copy-pasting.'),
        ),
    ]
