# Generated by Django 6.0.1 on 2026-01-31 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_evaluation_comparison_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='quality_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='quality_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
